<?php

/*
 * AlcedisMED
 * Copyright (C) 2010-2016  Alcedis GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */ 

$this
   ->showFieldIn(
      'diagnose_seite',
      array('b', 'lu', 'sst')
   )
   ->hideFieldIn(
      array(
         'schnellschnitt',
         'schnellschnitt_dauer'
      ),
      array('leu', 'snst')
   )
   ->showFieldIn(
      array(
         'art_transplantation_autolog',
         'art_transplantation_allogen_v',
         'art_transplantation_allogen_nv',
         'art_transplantation_syngen',
         'verwandschaftsgrad',
         'stammzellenmobilisierung',
         'leukapheresen_anzahl',
         'stamm_sep_datum',
         'stamm_sep_menge',
         'stamm_sep_menge_absolut',
         'stamm_sep_cd34_konz',
         'stamm_sep_cd34_konz_absolut',
         'stamm_purging',
         'stamm_purging_text',
         'chim1_datum',
         'chim1_wert',
         'chim2_datum',
         'chim2_wert',
         'chim3_datum',
         'chim3_wert',
         'chim4_datum',
         'chim4_wert',
         'dli1_datum',
         'dli1_wert',
         'dli2_datum',
         'dli2_wert',
         'erholung_leukozyten_datum',
         'erholung_granulozyten_datum',
         'erholung_thrombozyten_datum',
         'erholung_gesamt_datum',
      ),
      array('leu', 'ly', 'snst')
   )
   ->showFieldIn(
      array(
         'art_rekonstruktion',
         'mark',
         'mark_mammo',
         'mark_sono',
         'mark_mrt',
         'mark_abstand',
         'intraop_roe',
         'intraop_roe_ergebnis',
         'intraop_sono',
         'intraop_sono_ergebnis',
         'intraop_mrt',
         'intraop_mrt_ergebnis',
         'postop_roentgen',
         'postop_roentgen_ergebnis',
         'postop_sono',
         'postop_sono_ergebnis',
         'postop_mrt',
         'postop_mrt_ergebnis',
         'axilla_sampling',
         'sln_parasternal',
         'sln_restaktivitaet',
         'axilla_nein_grund',
         'sln_nein_grund',
         'sentinel_nicht_detektierbar',
      ),
      'b'
   )
   ->showFieldIn(
      array(
         'hypertherme_perfusion',
         'plastischer_verschluss',
         'lokalisation'
      ),
      'h'
   )
   ->showFieldIn(
      array(
         'sln_schnellschnitt',
         'sln_schnellschnitt_befall',
         'sln_schnellschnitt_dauer_versendung',
         'sln_schnellschnitt_dauer_eingang'
      ),
      array('b', 'gt')
   )
   ->showFieldIn(
      array(
         'sln_markierung',
         'sln_anzahl',
      ),
      array('b', 'gt', 'h')
   )
   ->showFieldIn(
      array(
         'polypen',
         'polypen_anz_gef',
         'polypen_anz_entf',
         'polypen_op_areal',
         'ther_koloskopie_vollstaendig',
         'tme',
         'pme',
         'stomaposition',
         'mesorektale_faszie'
      ),
      'd'
   )
   ->showFieldIn(
      array(
         'art_staging',
         'laparotomie',
         'peritonealzytologie',
         'peritonealbiopsie',
         'adnexexstirpation',
         'hysterektomie',
         'omentektomie',
         'lymphonodektomie',
         'aszites_volumen',
         'peritonealkarzinose_darm',
         'peritonealkarzinose_becken',
         'peritonealkarzinose_mittelbauch',
         'peritonealkarzinose_zwerchfell',
         'urologie_bet',
         'chirurgie_bet',
         'tumorlast_a1',
         'tumorlast_a2',
         'tumorlast_a3',
         'tumorlast_b1',
         'tumorlast_b2',
         'tumorlast_b3',
         'tumorlast_c1',
         'tumorlast_c2',
         'tumorlast_c3',
         'tumorrest',
         'tumorrest_groesse',
         'tumorrest_detail',
         'tumorrest_a1',
         'tumorrest_a2',
         'tumorrest_a3',
         'tumorrest_b1',
         'tumorrest_b2',
         'tumorrest_b3',
         'tumorrest_c1',
         'tumorrest_c2',
         'tumorrest_c3',
         'r0limit_aetas',
         'r0limit_komplikation',
         'r0limit_lokalisation',
         'r0limit_lokalisation_text',
         'r0limit_wunsch',
         'r0limit_wunsch_text',
         'r0limit_sonstige',
         'r0limit_sonstige_text',
         'befall_ovar',
         'befall_ovar_rest',
         'befall_ovar_seite',
         'befall_tube',
         'befall_tube_rest',
         'befall_tube_seite',
         'befall_milz',
         'befall_milz_rest',
         'befall_lk',
         'befall_lk_rest',
         'befall_ureter',
         'befall_ureter_rest',
         'befall_douglas',
         'befall_douglas_rest',
         'befall_vaginalstumpf',
         'befall_vaginalstumpf_rest',
         'befall_duenndarm',
         'befall_duenndarm_rest',
         'befall_zwerchfell',
         'befall_zwerchfell_rest',
         'befall_magen',
         'befall_magen_rest',
         'befall_lsm',
         'befall_lsm_rest',
         'befall_blasenwand',
         'befall_blasenwand_rest',
         'befall_beckenwand',
         'befall_beckenwand_rest',
         'befall_mesenterium',
         'befall_mesenterium_rest',
         'befall_dickdarm',
         'befall_dickdarm_rest',
         'befall_dickdarmschleimhaut',
         'befall_dickdarmschleimhaut_rest',
         'befall_omentum_majus',
         'befall_omentum_majus_rest',
         'befall_bauchwand',
         'befall_bauchwand_rest',
         'befall_blasenschleimhaut',
         'befall_blasenschleimhaut_rest',
         'befall_uterus',
         'befall_uterus_rest',
         'befall_bursa',
         'befall_bursa_rest',
         'befall_vagina',
         'befall_vagina_rest',
         'befall_portio',
         'befall_portio_rest',
         'befall_cervix',
         'befall_cervix_rest',
         'befall_vulva',
         'befall_vulva_rest',
         'befall_urethra',
         'befall_urethra_rest',
         'befall_sonst',
         'befall_sonst_text'
      ),
      'gt'
   )
   ->showFieldIn(
      array(
         'op_verfahren',
         'datum_katheterentfernung',
         'cystogramm1',
         'cystogramm2',
         'leckage_primaer',
         'leckage_sekundaer',
         'cf_entfernung',
         'dk_entfernung',
         'dk_neuanlage',
         'dk_entlassung',
         'lymphocele',
         'lymphocele_detail',
         'wundabstrich',
         'wundabstrich_ergebnis',
         'nerverhalt_seite',
         'lymphadenektomie_methode_prostata',
         'blasenkatheter'
      ),
      'p'
   )
   ->showFieldIn(
      array(
         'res_oberlappen',
         'res_mittellappen',
         'res_unterlappen'
      ),
      'lu'
   );
?>
