{*
AlcedisMED
Copyright (C) 2010-2016  Alcedis GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*} 

<?xml version="1.0" encoding="UTF-8"?>
<PCaPatienten>
    <InfoXML>
        <DatumXML>{$data.InfoXML.DatumXML}</DatumXML>
        {if strlen($data.InfoXML.NameTudokusys) > 0}
        <NameTudokusys>{$data.InfoXML.NameTudokusys}</NameTudokusys>
        {/if}
        {if strlen($data.InfoXML.VersionTudokusys) > 0}
        <VersionTudokusys>{$data.InfoXML.VersionTudokusys}</VersionTudokusys>
        {/if}
    </InfoXML>
    {foreach from=$data.patients item=patient}
    <Patient>
        <Stammdaten>
            {if strlen($patient.A.PatientID) > 0}
            <PatientID>{$patient.A.PatientID}</PatientID>
            {/if}
            <Geschlecht>{$patient.A.Geschlecht}</Geschlecht>
            <GeburtsJahr>{$patient.A.GeburtsJahr}</GeburtsJahr>
            <GeburtsMonat>{$patient.A.GeburtsMonat}</GeburtsMonat>
            <GeburtsTag>{$patient.A.GeburtsTag}</GeburtsTag>
            <Organ>{$patient.A.Organ}</Organ>
            <RegNr>{$patient.A.RegNr}</RegNr>
            <HauptNebenStandort>{$patient.A.HauptNebenStandort}</HauptNebenStandort>
        </Stammdaten>
        <PraeinterventionellerZeitraum>
            <ErstdiagnostikPrimaertumor>
                <DatumErstdiagnosePrimaertumor>{$patient.B.ErstdiagnostikPrimaertumor.DatumErstdiagnosePrimaertumor}</DatumErstdiagnosePrimaertumor>
                <Diagnosesicherheit>{$patient.B.ErstdiagnostikPrimaertumor.Diagnosesicherheit}</Diagnosesicherheit>
                <TumordiagnoseICD10>{$patient.B.ErstdiagnostikPrimaertumor.TumordiagnoseICD10}</TumordiagnoseICD10>
                <HauptlokalisationICDO3>{$patient.B.ErstdiagnostikPrimaertumor.HauptlokalisationICDO3}</HauptlokalisationICDO3>
                <praeTcp>{$patient.B.ErstdiagnostikPrimaertumor.praeTcp}</praeTcp>
                <praeT>{$patient.B.ErstdiagnostikPrimaertumor.praeT}</praeT>
                <praeNcp>{$patient.B.ErstdiagnostikPrimaertumor.praeNcp}</praeNcp>
                <praeN>{$patient.B.ErstdiagnostikPrimaertumor.praeN}</praeN>
                <praeMcp>{$patient.B.ErstdiagnostikPrimaertumor.praeMcp}</praeMcp>
                <praeM>{$patient.B.ErstdiagnostikPrimaertumor.praeM}</praeM>
                <PSADatum>{$patient.B.ErstdiagnostikPrimaertumor.PSADatum}</PSADatum>
                <PSAWert>{$patient.B.ErstdiagnostikPrimaertumor.PSAWert}</PSAWert>
                <BiopsieDatum>{$patient.B.ErstdiagnostikPrimaertumor.BiopsieDatum}</BiopsieDatum>
                <BiopsiePerineuraleInvasion>{$patient.B.ErstdiagnostikPrimaertumor.BiopsiePerineuraleInvasion}</BiopsiePerineuraleInvasion>
                <ICDOHistologie>{$patient.B.ErstdiagnostikPrimaertumor.ICDOHistologie}</ICDOHistologie>
                <BiopsieAS>{$patient.B.ErstdiagnostikPrimaertumor.BiopsieAS}</BiopsieAS>
                <GleasonScoreWert1>{$patient.B.ErstdiagnostikPrimaertumor.GleasonScoreWert1}</GleasonScoreWert1>
                <GleasonScoreWert2>{$patient.B.ErstdiagnostikPrimaertumor.GleasonScoreWert2}</GleasonScoreWert2>
                <Grading>{$patient.B.ErstdiagnostikPrimaertumor.Grading}</Grading>
                <BefundPathologieVollstaendig>{$patient.B.ErstdiagnostikPrimaertumor.BefundPathologieVollstaendig}</BefundPathologieVollstaendig>
                <Blasenkarzinom>{$patient.B.ErstdiagnostikPrimaertumor.Blasenkarzinom}</Blasenkarzinom>
                <DKGPatientenfragebogenDatum>{$patient.B.ErstdiagnostikPrimaertumor.DKGPatientenfragebogenDatum}</DKGPatientenfragebogenDatum>
                <Kontinenz>{$patient.B.ErstdiagnostikPrimaertumor.Kontinenz}</Kontinenz>
                <Potenz>{$patient.B.ErstdiagnostikPrimaertumor.Potenz}</Potenz>
                <Lebensqualitaet>{$patient.B.ErstdiagnostikPrimaertumor.Lebensqualitaet}</Lebensqualitaet>
                <Gesundheitszustand>{$patient.B.ErstdiagnostikPrimaertumor.Gesundheitszustand}</Gesundheitszustand>
            </ErstdiagnostikPrimaertumor>
            <Familienanamnese>
                <FamilienangehoerigeGrad1PCa>{$patient.B.Familienanamnese.FamilienangehoerigeGrad1PCa}</FamilienangehoerigeGrad1PCa>
                <Grad1juengerals60>{$patient.B.Familienanamnese.Grad1juengerals60}</Grad1juengerals60>
                <FamilienangehoerigeGrad2PCa>{$patient.B.Familienanamnese.FamilienangehoerigeGrad2PCa}</FamilienangehoerigeGrad2PCa>
                <FamilienangehoerigeGrad3PCa>{$patient.B.Familienanamnese.FamilienangehoerigeGrad3PCa}</FamilienangehoerigeGrad3PCa>
            </Familienanamnese>
            <KrebserkrankungenVorErstdiagnose>
                <RelevanteKrebserkrankungen>{$patient.B.KrebserkrankungenVorErstdiagnose.RelevanteKrebserkrankungen}</RelevanteKrebserkrankungen>
                <JahrRelevanteKrebserkrankungen>{$patient.B.KrebserkrankungenVorErstdiagnose.JahrRelevanteKrebserkrankungen}</JahrRelevanteKrebserkrankungen>
                <NichtRelevanteKrebserkrankungen>{$patient.B.KrebserkrankungenVorErstdiagnose.NichtRelevanteKrebserkrankungen}</NichtRelevanteKrebserkrankungen>
                <JahrNichtRelevanteKrebserkrankungen>{$patient.B.KrebserkrankungenVorErstdiagnose.JahrNichtRelevanteKrebserkrankungen}</JahrNichtRelevanteKrebserkrankungen>
            </KrebserkrankungenVorErstdiagnose>
            <PatientUnterBeobachtung>
                <Zentrumspatient>{$patient.B.PatientUnterBeobachtung.Zentrumspatient}</Zentrumspatient>
                <VorstellungImZentrum>{$patient.B.PatientUnterBeobachtung.VorstellungImZentrum}</VorstellungImZentrum>
                <DatumVorstellungImZentrum>{$patient.B.PatientUnterBeobachtung.DatumVorstellungImZentrum}</DatumVorstellungImZentrum>
                <PatientInZentrumEingebracht>{$patient.B.PatientUnterBeobachtung.PatientInZentrumEingebracht}</PatientInZentrumEingebracht>
                <Therapiestrategie>{$patient.B.PatientUnterBeobachtung.Therapiestrategie}</Therapiestrategie>
                <EinwilligungDokumentationInTumordokumentation>{$patient.B.PatientUnterBeobachtung.EinwilligungDokumentationInTumordokumentation}</EinwilligungDokumentationInTumordokumentation>
                <EinwilligungVersand>{$patient.B.PatientUnterBeobachtung.EinwilligungVersand}</EinwilligungVersand>
                <EinwilligigungMeldungKKREKR>{$patient.B.PatientUnterBeobachtung.EinwilligigungMeldungKKREKR}</EinwilligigungMeldungKKREKR>
                <FalldatensatzVollstaendig>{$patient.B.PatientUnterBeobachtung.FalldatensatzVollstaendig}</FalldatensatzVollstaendig>
            </PatientUnterBeobachtung>
            <Prozess>
                <DatumStudie>{$patient.B.Prozess.DatumStudie}</DatumStudie>
                <StudienTyp>{$patient.B.Prozess.StudienTyp}</StudienTyp>
                <PsychoonkologischeBetreuung>{$patient.B.Prozess.PsychoonkologischeBetreuung}</PsychoonkologischeBetreuung>
                <BeratungSozialdienst>{$patient.B.Prozess.BeratungSozialdienst}</BeratungSozialdienst>
                <PatientInMorbiditaetskonferenzVorgestellt>{$patient.B.Prozess.PatientInMorbiditaetskonferenzVorgestellt}</PatientInMorbiditaetskonferenzVorgestellt>
            </Prozess>
            {foreach from=$patient.B.FollowUpPraetherapeutischerTumorkonferenz item=FollowUpPraetherapeutischerTumorkonferenz}
            <FollowUpPraetherapeutischerTumorkonferenz>
                <Datum>{$FollowUpPraetherapeutischerTumorkonferenz.Datum}</Datum>
                <Quelle>{$FollowUpPraetherapeutischerTumorkonferenz.Quelle}</Quelle>
                <Vitalstatus>{$FollowUpPraetherapeutischerTumorkonferenz.Vitalstatus}</Vitalstatus>
                <KontrolluntersuchungTyp>{$FollowUpPraetherapeutischerTumorkonferenz.KontrolluntersuchungTyp}</KontrolluntersuchungTyp>
                <PSAWert>{$FollowUpPraetherapeutischerTumorkonferenz.PSAWert}</PSAWert>
                <Tumorstatus>{$FollowUpPraetherapeutischerTumorkonferenz.Tumorstatus}</Tumorstatus>
                <DKGFragebogenEingereicht>{$FollowUpPraetherapeutischerTumorkonferenz.DKGFragebogenEingereicht}</DKGFragebogenEingereicht>
                <Kontinenz>{$FollowUpPraetherapeutischerTumorkonferenz.Kontinenz}</Kontinenz>
                <Potenz>{$FollowUpPraetherapeutischerTumorkonferenz.Potenz}</Potenz>
                <Lebensqualitaet>{$FollowUpPraetherapeutischerTumorkonferenz.Lebensqualitaet}</Lebensqualitaet>
                <Gesundheitszustand>{$FollowUpPraetherapeutischerTumorkonferenz.Gesundheitszustand}</Gesundheitszustand>
                <DiagnoseFernmetastasierung>{$FollowUpPraetherapeutischerTumorkonferenz.DiagnoseFernmetastasierung}</DiagnoseFernmetastasierung>
                <DiagnoseZweittumor>{$FollowUpPraetherapeutischerTumorkonferenz.DiagnoseZweittumor}</DiagnoseZweittumor>
            </FollowUpPraetherapeutischerTumorkonferenz>
            {/foreach}
        </PraeinterventionellerZeitraum>
        <Primaerintervention>
            <DiagnostikVorPrimaerintervention>
                <praeTcp>{$patient.C.DiagnostikVorPrimaerintervention.praeTcp}</praeTcp>
                <praeT>{$patient.C.DiagnostikVorPrimaerintervention.praeT}</praeT>
                <praeNcp>{$patient.C.DiagnostikVorPrimaerintervention.praeNcp}</praeNcp>
                <praeN>{$patient.C.DiagnostikVorPrimaerintervention.praeN}</praeN>
                <praeMcp>{$patient.C.DiagnostikVorPrimaerintervention.praeMcp}</praeMcp>
                <praeM>{$patient.C.DiagnostikVorPrimaerintervention.praeM}</praeM>
                <PSADatum>{$patient.C.DiagnostikVorPrimaerintervention.PSADatum}</PSADatum>
                <PSAWert>{$patient.C.DiagnostikVorPrimaerintervention.PSAWert}</PSAWert>
                <BiopsieDatum>{$patient.C.DiagnostikVorPrimaerintervention.BiopsieDatum}</BiopsieDatum>
                <BiopsiePerineuraleInvasion>{$patient.C.DiagnostikVorPrimaerintervention.BiopsiePerineuraleInvasion}</BiopsiePerineuraleInvasion>
                <ICDOHistologie>{$patient.C.DiagnostikVorPrimaerintervention.ICDOHistologie}</ICDOHistologie>
                <GleasonScoreWert1>{$patient.C.DiagnostikVorPrimaerintervention.GleasonScoreWert1}</GleasonScoreWert1>
                <GleasonScoreWert2>{$patient.C.DiagnostikVorPrimaerintervention.GleasonScoreWert2}</GleasonScoreWert2>
                <Grading>{$patient.C.DiagnostikVorPrimaerintervention.Grading}</Grading>
                <BefundPathologieVollstaendig>{$patient.C.DiagnostikVorPrimaerintervention.BefundPathologieVollstaendig}</BefundPathologieVollstaendig>
                <Blasenkarzinom>{$patient.C.DiagnostikVorPrimaerintervention.Blasenkarzinom}</Blasenkarzinom>
                <DKGPatientenfragebogenDatum>{$patient.C.DiagnostikVorPrimaerintervention.DKGPatientenfragebogenDatum}</DKGPatientenfragebogenDatum>
                <Kontinenz>{$patient.C.DiagnostikVorPrimaerintervention.Kontinenz}</Kontinenz>
                <Potenz>{$patient.C.DiagnostikVorPrimaerintervention.Potenz}</Potenz>
                <Lebensqualitaet>{$patient.C.DiagnostikVorPrimaerintervention.Lebensqualitaet}</Lebensqualitaet>
                <Gesundheitszustand>{$patient.C.DiagnostikVorPrimaerintervention.Gesundheitszustand}</Gesundheitszustand>
            </DiagnostikVorPrimaerintervention>
            <PatientInPrimaertherapie>
                <Zentrumspatient>{$patient.C.PatientInPrimaertherapie.Zentrumspatient}</Zentrumspatient>
                <PraetherapeutischeVorstellung>{$patient.C.PatientInPrimaertherapie.PraetherapeutischeVorstellung}</PraetherapeutischeVorstellung>
                <DatumVorstellungImZentrum>{$patient.C.PatientInPrimaertherapie.DatumVorstellungImZentrum}</DatumVorstellungImZentrum>
                <VorstellungUeberLeistungserbringer>{$patient.C.PatientInPrimaertherapie.VorstellungUeberLeistungserbringer}</VorstellungUeberLeistungserbringer>
                <EinwilligungDokumentationInTumordokumentation>{$patient.C.PatientInPrimaertherapie.EinwilligungDokumentationInTumordokumentation}</EinwilligungDokumentationInTumordokumentation>
                <EinwilligungVersand>{$patient.C.PatientInPrimaertherapie.EinwilligungVersand}</EinwilligungVersand>
                <EinwilligigungMeldungKKREKR>{$patient.C.PatientInPrimaertherapie.EinwilligigungMeldungKKREKR}</EinwilligigungMeldungKKREKR>
                <FalldatensatzVollstaendig>{$patient.C.PatientInPrimaertherapie.FalldatensatzVollstaendig}</FalldatensatzVollstaendig>
            </PatientInPrimaertherapie>
            <Operation>
                <DatumOperation>{$patient.C.Operation.DatumOperation}</DatumOperation>
                <OPSCode>{$patient.C.Operation.OPSCode}</OPSCode>
                <Verfahren>{$patient.C.Operation.Verfahren}</Verfahren>
                <Erstoperateur>{$patient.C.Operation.Erstoperateur}</Erstoperateur>
                <Zweitoperateur>{$patient.C.Operation.Zweitoperateur}</Zweitoperateur>
                <Revisionseingriff>{$patient.C.Operation.Revisionseingriff}</Revisionseingriff>
                <RevisionseingriffDatum>{$patient.C.Operation.RevisionseingriffDatum}</RevisionseingriffDatum>
                <PostoperativeWundinfektion>{$patient.C.Operation.PostoperativeWundinfektion}</PostoperativeWundinfektion>
                <PostoperativeWundinfektionDatum>{$patient.C.Operation.PostoperativeWundinfektionDatum}</PostoperativeWundinfektionDatum>
                <NervenerhaltendeOperation>{$patient.C.Operation.NervenerhaltendeOperation}</NervenerhaltendeOperation>
                <CalvienDindoGrad>{$patient.C.Operation.CalvienDindoGrad}</CalvienDindoGrad>
                <DatumKomplikation>{$patient.C.Operation.DatumKomplikation}</DatumKomplikation>
            </Operation>
            <PostoperativeHistologie>
                <PraefixY>{$patient.C.PostoperativeHistologie.PraefixY}</PraefixY>
                <pT>{$patient.C.PostoperativeHistologie.pT}</pT>
                <pN>{$patient.C.PostoperativeHistologie.pN}</pN>
                <pM>{$patient.C.PostoperativeHistologie.pM}</pM>
                <GleasonScoreWert1>{$patient.C.PostoperativeHistologie.GleasonScoreWert1}</GleasonScoreWert1>
                <GleasonScoreWert2>{$patient.C.PostoperativeHistologie.GleasonScoreWert2}</GleasonScoreWert2>
                <Grading>{$patient.C.PostoperativeHistologie.Grading}</Grading>
                <PerineuraleInvasion>{$patient.C.PostoperativeHistologie.PerineuraleInvasion}</PerineuraleInvasion>
                <AnzahlUntersuchtenLymphknoten>{$patient.C.PostoperativeHistologie.AnzahlUntersuchtenLymphknoten}</AnzahlUntersuchtenLymphknoten>
                <AnzahlMaligneBefallenenLymphknoten>{$patient.C.PostoperativeHistologie.AnzahlMaligneBefallenenLymphknoten}</AnzahlMaligneBefallenenLymphknoten>
                <Lymphgefaessinvasion>{$patient.C.PostoperativeHistologie.Lymphgefaessinvasion}</Lymphgefaessinvasion>
                <Veneninvasion>{$patient.C.PostoperativeHistologie.Veneninvasion}</Veneninvasion>
                <ICDO3Histologie>{$patient.C.PostoperativeHistologie.ICDO3Histologie}</ICDO3Histologie>
                <PSRLokaleRadikalitaet>{$patient.C.PostoperativeHistologie.PSRLokaleRadikalitaet}</PSRLokaleRadikalitaet>
            </PostoperativeHistologie>
            <PostoperativesStaging>
                <TumordiagnoseICD10>{$patient.C.PostoperativesStaging.TumordiagnoseICD10}</TumordiagnoseICD10>
                <cM>{$patient.C.PostoperativesStaging.cM}</cM>
            </PostoperativesStaging>
            <PostoperativeTumorkonferenz>
                <Vorstellung>{$patient.C.PostoperativeTumorkonferenz.Vorstellung}</Vorstellung>
                <Datum>{$patient.C.PostoperativeTumorkonferenz.Datum}</Datum>
            </PostoperativeTumorkonferenz>
            <PerkutaneStrahlentherapie>
                <Therapiezeitpunkt>{$patient.C.PerkutaneStrahlentherapie.Therapiezeitpunkt}</Therapiezeitpunkt>
                <Therapieintention>{$patient.C.PerkutaneStrahlentherapie.Therapieintention}</Therapieintention>
                <BeginnDatum>{$patient.C.PerkutaneStrahlentherapie.BeginnDatum}</BeginnDatum>
                <GesamtdosisInGray>{$patient.C.PerkutaneStrahlentherapie.GesamtdosisInGray}</GesamtdosisInGray>
                <EndeDatum>{$patient.C.PerkutaneStrahlentherapie.EndeDatum}</EndeDatum>
                <GrundBeendigungStrahlentherapie>{$patient.C.PerkutaneStrahlentherapie.GrundBeendigungStrahlentherapie}</GrundBeendigungStrahlentherapie>
            </PerkutaneStrahlentherapie>
            <LDRBrachytherapie>
                <Datum>{$patient.C.LDRBrachytherapie.Datum}</Datum>
                <GesamtdosisInGray>{$patient.C.LDRBrachytherapie.GesamtdosisInGray}</GesamtdosisInGray>
                <GrayBeiD90>{$patient.C.LDRBrachytherapie.GrayBeiD90}</GrayBeiD90>
            </LDRBrachytherapie>
            <HDRBrachytherapie>
                <BeginnDatum>{$patient.C.HDRBrachytherapie.BeginnDatum}</BeginnDatum>
                <GesamtdosisInGray>{$patient.C.HDRBrachytherapie.GesamtdosisInGray}</GesamtdosisInGray>
                <EndeDatum>{$patient.C.HDRBrachytherapie.EndeDatum}</EndeDatum>
                <GrundBeendigungBrachytherapie>{$patient.C.HDRBrachytherapie.GrundBeendigungBrachytherapie}</GrundBeendigungBrachytherapie>
            </HDRBrachytherapie>
            <Chemotherapie>
                <BeginnDatum>{$patient.C.Chemotherapie.BeginnDatum}</BeginnDatum>
                <EndeDatum>{$patient.C.Chemotherapie.EndeDatum}</EndeDatum>
                <GrundBeendigungChemotherapie>{$patient.C.Chemotherapie.GrundBeendigungChemotherapie}</GrundBeendigungChemotherapie>
            </Chemotherapie>
            <Hormontherapie>
                <Therapiezeitpunkt>{$patient.C.Hormontherapie.Therapiezeitpunkt}</Therapiezeitpunkt>
                <Therapieintention>{$patient.C.Hormontherapie.Therapieintention}</Therapieintention>
                <TherapieArt>{$patient.C.Hormontherapie.TherapieArt}</TherapieArt>
                <BeginnDatum>{$patient.C.Hormontherapie.BeginnDatum}</BeginnDatum>
                <EndeDatum>{$patient.C.Hormontherapie.EndeDatum}</EndeDatum>
                <GrundBeendigungHormontherapie>{$patient.C.Hormontherapie.GrundBeendigungHormontherapie}</GrundBeendigungHormontherapie>
            </Hormontherapie>
            <Immuntherapie>
                <BeginnDatum>{$patient.C.Immuntherapie.BeginnDatum}</BeginnDatum>
                <EndeDatum>{$patient.C.Immuntherapie.EndeDatum}</EndeDatum>
                <GrundBeendigungImmuntherapie>{$patient.C.Immuntherapie.GrundBeendigungImmuntherapie}</GrundBeendigungImmuntherapie>
            </Immuntherapie>
            <WeitereTherapien>
                <SupportiveTherapieDatum>{$patient.C.WeitereTherapien.SupportiveTherapieDatum}</SupportiveTherapieDatum>
                <HIFUTherapieDatum>{$patient.C.WeitereTherapien.HIFUTherapieDatum}</HIFUTherapieDatum>
                <KyrotherapieDatum>{$patient.C.WeitereTherapien.KyrotherapieDatum}</KyrotherapieDatum>
                <HyperthermieDatum>{$patient.C.WeitereTherapien.HyperthermieDatum}</HyperthermieDatum>
            </WeitereTherapien>
            <PosttherapeutischeTumorkonferenz>
                <Vorstellung>{$patient.C.PosttherapeutischeTumorkonferenz.Vorstellung}</Vorstellung>
                <Datum>{$patient.C.PosttherapeutischeTumorkonferenz.Datum}</Datum>
            </PosttherapeutischeTumorkonferenz>
            <AbschlussPrimaerintervention>
                <CalvienDindoGrad>{$patient.C.AbschlussPrimaerintervention.CalvienDindoGrad}</CalvienDindoGrad>
                <DatumKomplikation>{$patient.C.AbschlussPrimaerintervention.DatumKomplikation}</DatumKomplikation>
            </AbschlussPrimaerintervention>
            <ProzessPrimaertherapie>
                <Studientyp>{$patient.C.ProzessPrimaertherapie.Studientyp}</Studientyp>
                <DatumStudie>{$patient.C.ProzessPrimaertherapie.DatumStudie}</DatumStudie>
                <PsychoonkologischeBetreuung>{$patient.C.ProzessPrimaertherapie.PsychoonkologischeBetreuung}</PsychoonkologischeBetreuung>
                <BeratungSozialdienst>{$patient.C.ProzessPrimaertherapie.BeratungSozialdienst}</BeratungSozialdienst>
                <PatientInMorbiditaetskonferenzvorgestellt>{$patient.C.ProzessPrimaertherapie.PatientInMorbiditaetskonferenzvorgestellt}</PatientInMorbiditaetskonferenzvorgestellt>
            </ProzessPrimaertherapie>
        </Primaerintervention>
        {foreach from=$patient.D.progressintervention item=progressintervention}
        <Progressintervention>
            <DiagnostikVorProgressintervention>
                <DatumDiagnoseProgress>{$progressintervention.DiagnostikVorProgressintervention.DatumDiagnoseProgress}</DatumDiagnoseProgress>
                <TumordiagnoseICD10>{$progressintervention.DiagnostikVorProgressintervention.TumordiagnoseICD10}</TumordiagnoseICD10>
                <HauptlokalisationICDO3>{$progressintervention.DiagnostikVorProgressintervention.HauptlokalisationICDO3}</HauptlokalisationICDO3>
                <PSAWert>{$progressintervention.DiagnostikVorProgressintervention.PSAWert}</PSAWert>
                <BiopsieDurchgefuehrt>{$progressintervention.DiagnostikVorProgressintervention.BiopsieDurchgefuehrt}</BiopsieDurchgefuehrt>
                <BiopsiePerineuraleInvasion>{$progressintervention.DiagnostikVorProgressintervention.BiopsiePerineuraleInvasion}</BiopsiePerineuraleInvasion>
                <ICDOHistologieMorphologie>{$progressintervention.DiagnostikVorProgressintervention.ICDOHistologieMorphologie}</ICDOHistologieMorphologie>
                <GleasonScoreWert1>{$progressintervention.DiagnostikVorProgressintervention.GleasonScoreWert1}</GleasonScoreWert1>
                <GleasonScoreWert2>{$progressintervention.DiagnostikVorProgressintervention.GleasonScoreWert2}</GleasonScoreWert2>
                <Grading>{$progressintervention.DiagnostikVorProgressintervention.Grading}</Grading>
                <DKGPatientenfragebogenDatum>{$progressintervention.DiagnostikVorProgressintervention.DKGPatientenfragebogenDatum}</DKGPatientenfragebogenDatum>
                <Kontinenz>{$progressintervention.DiagnostikVorProgressintervention.Kontinenz}</Kontinenz>
                <Potenz>{$progressintervention.DiagnostikVorProgressintervention.Potenz}</Potenz>
                <Lebensqualitaet>{$progressintervention.DiagnostikVorProgressintervention.Lebensqualitaet}</Lebensqualitaet>
                <Gesundheitszustand>{$progressintervention.DiagnostikVorProgressintervention.Gesundheitszustand}</Gesundheitszustand>
            </DiagnostikVorProgressintervention>
            <PatientInProgressintervention>
                <Zentrumspatient>{$progressintervention.PatientInProgressintervention.Zentrumspatient}</Zentrumspatient>
                <PraetherapeutischeVorstellung>{$progressintervention.PatientInProgressintervention.PraetherapeutischeVorstellung}</PraetherapeutischeVorstellung>
                <DatumVorstellungImZentrum>{$progressintervention.PatientInProgressintervention.DatumVorstellungImZentrum}</DatumVorstellungImZentrum>
                <VorstellungUeberLeistungserbringer>{$progressintervention.PatientInProgressintervention.VorstellungUeberLeistungserbringer}</VorstellungUeberLeistungserbringer>
                <FalldatensatzVollstaendig>{$progressintervention.PatientInProgressintervention.FalldatensatzVollstaendig}</FalldatensatzVollstaendig>
            </PatientInProgressintervention>
            <Prostatektomie>
                <Datum>{$progressintervention.Prostatektomie.Datum}</Datum>
                <OPSCode>{$progressintervention.Prostatektomie.OPSCode}</OPSCode>
                <Verfahren>{$progressintervention.Prostatektomie.Verfahren}</Verfahren>
                <Erstoperateur>{$progressintervention.Prostatektomie.Erstoperateur}</Erstoperateur>
                <Zweitoperateur>{$progressintervention.Prostatektomie.Zweitoperateur}</Zweitoperateur>
                <Revisionseingriff>{$progressintervention.Prostatektomie.Revisionseingriff}</Revisionseingriff>
                <RevisionseingriffDatum>{$progressintervention.Prostatektomie.RevisionseingriffDatum}</RevisionseingriffDatum>
                <PostoperativeWundinfektion>{$progressintervention.Prostatektomie.PostoperativeWundinfektion}</PostoperativeWundinfektion>
                <PostoperativeWundinfektionDatum>{$progressintervention.Prostatektomie.PostoperativeWundinfektionDatum}</PostoperativeWundinfektionDatum>
                <NervenerhaltendeOperation>{$progressintervention.Prostatektomie.NervenerhaltendeOperation}</NervenerhaltendeOperation>
            </Prostatektomie>
            <PostoperativeHistologie>
                <PostopResidualtumorLokale>{$progressintervention.PostoperativeHistologie.PostopResidualtumorLokale}</PostopResidualtumorLokale>
            </PostoperativeHistologie>
            <PostoperativeTumorkonferenz>
                <Vorstellung>{$progressintervention.PostoperativeTumorkonferenz.Vorstellung}</Vorstellung>
                <Datum>{$progressintervention.PostoperativeTumorkonferenz.Datum}</Datum>
            </PostoperativeTumorkonferenz>
            <ProzessProgressintervention>
                <Studientyp>{$progressintervention.ProzessProgressintervention.Studientyp}</Studientyp>
                <DatumStudie>{$progressintervention.ProzessProgressintervention.DatumStudie}</DatumStudie>
                <PsychoonkologischeBetreuung>{$progressintervention.ProzessProgressintervention.PsychoonkologischeBetreuung}</PsychoonkologischeBetreuung>
                <BeratungSozialdienst>{$progressintervention.ProzessProgressintervention.BeratungSozialdienst}</BeratungSozialdienst>
                <PatientInMorbiditaetskonferenzvorgestellt>{$progressintervention.ProzessProgressintervention.PatientInMorbiditaetskonferenzvorgestellt}</PatientInMorbiditaetskonferenzvorgestellt>
            </ProzessProgressintervention>
        </Progressintervention>
        {/foreach}
        {foreach from=$patient.E.followup item=followup}
        <FollowUp>
            <Datum>{$followup.Datum}</Datum>
            <Quelle>{$followup.Quelle}</Quelle>
            <Vitalstatus>{$followup.Vitalstatus}</Vitalstatus>
            <Tumorstatus>{$followup.Tumorstatus}</Tumorstatus>
            <PSAWert>{$followup.PSAWert}</PSAWert>
            <DKGFragebogenEingereicht>{$followup.DKGFragebogenEingereicht}</DKGFragebogenEingereicht>
            <Kontinenz>{$followup.Kontinenz}</Kontinenz>
            <Potenz>{$followup.Potenz}</Potenz>
            <Lebensqualitaet>{$followup.Lebensqualitaet}</Lebensqualitaet>
            <Gesundheitszustand>{$followup.Gesundheitszustand}</Gesundheitszustand>
            <DiagnoseLokalrezidiv>{$followup.DiagnoseLokalrezidiv}</DiagnoseLokalrezidiv>
            <DiagnoseBiochemischenRezidiv>{$followup.DiagnoseBiochemischenRezidiv}</DiagnoseBiochemischenRezidiv>
            <DiagnoseFernmetastasierung>{$followup.DiagnoseFernmetastasierung}</DiagnoseFernmetastasierung>
            <Zweittumor>{$followup.Zweittumor}</Zweittumor>
        </FollowUp>
        {/foreach}
    </Patient>
    {/foreach}
</PCaPatienten>
