<?php

/*
 * AlcedisMED
 * Copyright (C) 2010-2016  Alcedis GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */ 

$fields = array(
   'eingriff_id'                          => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' , 'type'  =>'hidden'  ,'ext' =>'', 'reference' => array('histologie', 'zytologie', 'komplikation')),
   'patient_id'                           => array('req' => 1,'size' =>'' ,'maxlen' =>' 11' , 'type'  =>'hidden'  ,'ext' =>'' ),
   'erkrankung_id'                        => array('req' => 1,'size' =>'' ,'maxlen' =>' 11' , 'type'  =>'hidden'  ,'ext' =>'' ),
   'datum'                                => array('req' => 1,'size' =>'' ,'maxlen' =>''    , 'type'  =>'date'    ,'ext' =>'' ),
   'notfall'                              => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type'  =>'check'   ,'ext' =>'' ),
   'org_id'                               => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type'  =>'query'   ,'ext' => $querys['query_org'], 'preselect' => 'org_id'),
   'operateur1_id'                        => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' , 'type' => 'picker'  , 'ext' => array( 'query' => $querys['query_user'], 'type' => 'arzt'),'preselect' => 'user.user_id' ),
   'operateur2_id'                        => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' , 'type' => 'picker'  , 'ext' => array( 'query' => $querys['query_user'], 'type' => 'arzt'),'preselect' => 'user.user_id' ),
   'therapieplan_id'                      => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' , 'type'  =>'query'   ,'ext' => $querys['query_therapieplan'],  'parent_status' => 'therapieplan'),
   'dauer'                                => array('req' => 0,'size' =>'2' ,'maxlen' =>''    , 'type'  =>'int'     ,'ext' =>'' ),
   'asa'                                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type'  =>'lookup'  ,'ext' => array('l_basic' => 'asa' ) ),
   'wundkontamination_cdc'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type'  =>'lookup'  ,'ext' => array('l_basic' => 'wundkontamination_cdc' ) ),
   'interdisziplinaer'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type'  =>'lookup'  ,'ext' => array('l_basic' => 'jn'  ) ),
   'urologie_bet'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'chirurgie_bet'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'diagnose_seite'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' => 'seite' ), 'default' => '-', 'null' => '-' ),
   'intention'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' => 'intention_eingriff' ) ),
   'art_diagnostik'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_staging'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_primaertumor'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_lk'                               => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_metastasen'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_rezidiv'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_nachresektion'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_transplantation_autolog'          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_transplantation_allogen_v'        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_transplantation_allogen_nv'       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_transplantation_syngen'           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'verwandschaftsgrad'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'verwandschaftsgrad') ),
   'art_revision'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_rekonstruktion'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'art_sonstige'                         => array('req' => 0,'size' =>'' ,'maxlen' =>' 255', 'type' =>'string'   ,'ext' =>'' ),
   'mark'                                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praeop_mark') ),
   'mark_mammo'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'mark_sono'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'mark_mrt'                             => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'mark_abstand'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'mark_abstand') ),
   'stomaposition'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'mesorektale_faszie'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' =>'' ),
   'schnellschnitt'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'schnellschnitt_dauer'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' =>'' ),
   'intraop_roe'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'intraop_roe_ergebnis'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'blasenkatheter'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'thromboseprophylaxe'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'antibiotikaprophylaxe'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'intraop_sono'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'intraop_sono_ergebnis'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'intraop_mrt'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'intraop_mrt_ergebnis'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'postop_roentgen'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'postop_roentgen_ergebnis'             => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'postop_sono'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'postop_sono_ergebnis'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'postop_mrt'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'postop_mrt_ergebnis'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'praep_ergebnis') ),
   'stammzellenmobilisierung'             => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'leukapheresen_anzahl'                 => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'stamm_sep_datum'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'stamm_sep_menge'                      => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'stamm_sep_menge_absolut'              => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'stamm_sep_cd34_konz'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'stamm_sep_cd34_konz_absolut'          => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'stamm_purging'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'stamm_purging_text'                   => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'chim1_datum'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'chim1_wert'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'chim2_datum'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'chim2_wert'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'chim3_datum'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'chim3_wert'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'chim4_datum'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'chim4_wert'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'dli1_datum'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'dli1_wert'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'dli2_datum'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'dli2_wert'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'erholung_leukozyten_datum'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'erholung_granulozyten_datum'          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'erholung_thrombozyten_datum'          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'erholung_gesamt_datum'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'axilla_sampling'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'axilla_nein_grund'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'axilla_nein_grund') ),
   'res_oberlappen'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'res_mittellappen'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'res_unterlappen'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tme'                                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'pme'                                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'ther_koloskopie_vollstaendig'         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn_ni') ),
   'op_verfahren'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'op_verfahren') ),
   'nerverhalt_seite'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'nerverhalt_seite') ),
   'lymphadenektomie_methode_prostata'    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'lymphadenektomie_methode_prostata') ),
   'intraop_bestrahlung'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'intraop_bestrahlung_dosis'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'float'    ,'ext' => '' ),
   'intraop_zytostatika'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'intraop_zytostatika_art'              => array('req' => 0,'size' =>'' ,'maxlen' =>'50'  , 'type' =>'string'   ,'ext' => '' ),
   'hypertherme_perfusion'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'plastischer_verschluss'               => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'laparotomie'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'peritonealzytologie'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'peritonealbiopsie'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'adnexexstirpation'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'seite')),
   'hysterektomie'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'omentektomie'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'omentektomie')),
   'lymphonodektomie'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'sln_nein_grund'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'sln_nein_grund') ),
   'sentinel_nicht_detektierbar'          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' =>'' ),
   'sln_markierung'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'sln_markierung') ),
   'sln_anzahl'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'sln_parasternal'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'sln_restaktivitaet'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'sln_schnellschnitt'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'sln_schnellschnitt_befall'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'sln_schnellschnitt_dauer_versendung'  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'sln_schnellschnitt_dauer_eingang'     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'blutverlust'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'polypen'                              => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'polypen_anz_gef'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'polypen_anz_entf'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'int'      ,'ext' => '' ),
   'polypen_op_areal'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'aszites_volumen'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'aszites_volumen') ),
   'peritonealkarzinose_darm'             => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'peritonealkarzinose') ),
   'peritonealkarzinose_becken'           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'peritonealkarzinose') ),
   'peritonealkarzinose_mittelbauch'      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'peritonealkarzinose') ),
   'peritonealkarzinose_zwerchfell'       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'peritonealkarzinose') ),
   'tumorlast_a1'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_a2'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_a3'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_b1'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_b2'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_b3'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_c1'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_c2'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorlast_c3'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'tumorrest_groesse'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'tumorrest_groesse') ),
   'tumorrest_detail'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'tumorrest_detail') ),
   'tumorrest_a1'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_a2'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_a3'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_b1'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_b2'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_b3'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_c1'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_c2'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'tumorrest_c3'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_aetas'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_komplikation'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_lokalisation'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_lokalisation_text'           => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'r0limit_wunsch'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_wunsch_text'                 => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'r0limit_sonstige'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'r0limit_sonstige_text'               => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'befall_ovar'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_ovar_rest'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_ovar_seite'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'seite') ),
   'befall_tube'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_tube_rest'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_tube_seite'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'seite') ),
   'befall_milz'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_milz_rest'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_lk'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_lk_rest'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_ureter'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_ureter_rest'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_douglas'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_douglas_rest'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vaginalstumpf'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vaginalstumpf_rest'           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_duenndarm'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_duenndarm_rest'               => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_zwerchfell'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_zwerchfell_rest'              => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_magen'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_magen_rest'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_lsm'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_lsm_rest'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_blasenwand'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_blasenwand_rest'              => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_beckenwand'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_beckenwand_rest'              => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_mesenterium'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_mesenterium_rest'             => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_dickdarm'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_dickdarm_rest'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_dickdarmschleimhaut'          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_dickdarmschleimhaut_rest'     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_omentum_majus'                => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_omentum_majus_rest'           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_bauchwand'                    => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_bauchwand_rest'               => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_blasenschleimhaut'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_blasenschleimhaut_rest'       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_uterus'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_uterus_rest'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_bursa'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_bursa_rest'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vagina'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vagina_rest'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_portio'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_portio_rest'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_cervix'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_cervix_rest'                  => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vulva'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_vulva_rest'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_urethra'                      => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_urethra_rest'                 => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_sonst'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'befall_sonst_text'                   => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'beatmung'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'beatmung_dauer'                      => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'intensiv'                            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'intensiv_dauer'                      => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'antibiotika'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'thrombose'                           => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'antibiotika_dauer'                   => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'transfusion'                         => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'check'    ,'ext' => '' ),
   'transfusion_anzahl_ek'               => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'transfusion_anzahl_tk'               => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'transfusion_anzahl_ffp'              => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'datum_drainageentfernung'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'datum_katheterentfernung'            => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'date'     ,'ext' => '' ),
   'cystogramm1'                         => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'cystogramm2'                         => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'leckage_primaer'                     => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'leckage_sekundaer'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'cf_entfernung'                       => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'dk_entfernung'                       => array('req' => 0,'size' =>'' ,'maxlen' =>'11'  , 'type' =>'int'      ,'ext' => '' ),
   'dk_neuanlage'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'dk_entlassung'                       => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'lymphocele'                          => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'lymphocele_detail'                   => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'lymphocele_detail') ),
   'wundabstrich'                        => array('req' => 0,'size' =>'' ,'maxlen' =>''    , 'type' =>'lookup'   ,'ext' => array('l_basic' =>'jn') ),
   'wundabstrich_ergebnis'               => array('req' => 0,'size' =>'' ,'maxlen' =>'255' , 'type' =>'string'   ,'ext' => '' ),
   'bem'                                 => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' ,'type' =>'textarea'  ,'ext' => '' ),
   'createuser'                          => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' ,'type' =>'hidden'    ,'ext' => '' ),
   'createtime'                          => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' ,'type' =>'hidden'    ,'ext' => '' ),
   'updateuser'                          => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' ,'type' =>'hidden'    ,'ext' => '' ),
   'updatetime'                          => array('req' => 0,'size' =>'' ,'maxlen' =>' 11' ,'type' =>'hidden'    ,'ext' => '' )
);

?>
