<?php

/*
 * AlcedisMED
 * Copyright (C) 2010-2016  Alcedis GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */ 

class dkgBValidations extends dkgBaseValidations
{
    public function __construct()
    {
        $this
            ->_setName('b')
            ->_activateForDisease('b')
            ->registerValidations()
        ;
    }

    public function registerValidations()
    {
        $this
            ->addValidation(dkgValidation::create('erkrankung')
                ->addField(dkgValidationField::create('zweiterkrankung')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('vorlage_studie')
                ->addField(dkgValidationField::create('ethikvotum')
                     ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('vorlage_therapie')
                ->addField(dkgValidationField::create('art'))
            )
            ->addValidation(dkgValidation::create('patient')
                ->addField(dkgValidationField::create('geschlecht'))
            )
            ->addValidation(dkgValidation::create('diagnose')
                ->addField(dkgValidationField::create('datum'))
            )
            ->addValidation(dkgValidation::create('eingriff')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('operateur1_id')
                    ->setCondition('$org_id == "$patientOrgId" || strlen($org_id) == 0')
                )
                ->addField(dkgValidationField::create('operateur2_id')
                    ->setCheck(false)
                    ->setCondition('($org_id == "$patientOrgId" || strlen($org_id) == 0) && in_array("1", array($art_primaertumor, $art_lk, $art_metastasen, $art_rezidiv, $art_nachresektion, $art_revision)) === true')
                )
                ->addField(dkgValidationField::create('diagnose_seite'))
                ->addField(dkgValidationField::create('art_primaertumor')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('art_rezidiv')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('art_revision')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('mark'))
                ->addField(dkgValidationField::create('schnellschnitt')
                    ->setCheck(false)
                    ->setCondition('$org_id == "$patientOrgId" && in_array("1", array($art_primaertumor, $art_lk, $art_metastasen, $art_rezidiv, $art_nachresektion, $art_revision)) === true')
                )
                ->addField(dkgValidationField::create('schnellschnitt_dauer')
                    ->setCheck(false)
                    ->setCondition('$schnellschnitt == "1"')
                )
                ->addField(dkgValidationField::create('intraop_roe'))
                ->addField(dkgValidationField::create('intraop_sono'))
                ->addDlist(dkgValidation::create('eingriff_ops')
                    ->addField(dkgValidationField::create('prozedur'))
                )
            )
            ->addValidation(dkgValidation::create('komplikation')
                ->addField(dkgValidationField::create('komplikation'))
                ->addField(dkgValidationField::create('eingriff_id')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('revisionsoperation'))
            )
            ->addValidation(dkgValidation::create('histologie')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('art'))
                ->addField(dkgValidationField::create('diagnose_seite')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_sentinel_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_sentinel_bef')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('therapieplan')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('grundlage'))
                ->addField(dkgValidationField::create('zeitpunkt'))
                ->addField(dkgValidationField::create('konferenz_patient_id')
                    ->setCondition('$grundlage == "tk" && appSettings::get("konferenz") === true')
                )
                ->addField(dkgValidationField::create('strahlen'))
                ->addField(dkgValidationField::create('strahlen_intention')
                    ->setCheck(false)
                    ->setCondition('$strahlen == "1"')
                )
                ->addField(dkgValidationField::create('chemo'))
                ->addField(dkgValidationField::create('chemo_intention')
                    ->setCheck(false)
                    ->setCondition('$chemo == "1"')
                )
                ->addField(dkgValidationField::create('immun'))
                ->addField(dkgValidationField::create('immun_intention')
                    ->setCheck(false)
                    ->setCondition('$immun == "1"')
                )
                ->addField(dkgValidationField::create('ah'))
                ->addField(dkgValidationField::create('ah_intention')
                    ->setCheck(false)
                    ->setCondition('$ah == "1"')
                )
            )
            ->addValidation(dkgValidation::create('therapie_systemisch')
                ->addField(dkgValidationField::create('intention'))
                ->addField(dkgValidationField::create('beginn')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('ende')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('andauernd')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('therapielinie')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('strahlentherapie')
                ->addField(dkgValidationField::create('intention'))
                ->addField(dkgValidationField::create('beginn')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('ende')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('andauernd')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('einzeldosis'))
                ->addField(dkgValidationField::create('gesamtdosis'))
                ->addField(dkgValidationField::create('boost'))
                ->addField(dkgValidationField::create('boostdosis')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('studie')
                ->addField(dkgValidationField::create('vorlage_studie_id'))
                ->addField(dkgValidationField::create('date')
                    ->setCondition('strlen($beginn) == 0')
                )
                ->addField(dkgValidationField::create('beginn')
                    ->setCondition('strlen($date) == 0')
                )
            )
            ->addValidation(dkgValidation::create('beratung')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('psychoonkologie'))
                ->addField(dkgValidationField::create('psychoonkologie_dauer')
                    ->setCondition('$psychoonkologie == 1')
                )
                ->addField(dkgValidationField::create('sozialdienst'))
            )
            ->addValidation(dkgValidation::create('fragebogen')
                ->addField(dkgValidationField::create('datum'))
            )
            ->addValidation(dkgValidation::create('nachsorge')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('response_klinisch')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('abschluss')
                ->addField(dkgValidationField::create('abschluss_grund'))
                ->addField(dkgValidationField::create('todesdatum')
                    ->setCheck(false)
                    ->setCondition('$abschluss_grund == "tot"')
                )
                ->addField(dkgValidationField::create('tod_tumorassoziation')
                    ->setCheck(false)
                    ->setCondition('$abschluss_grund == "tot"')
                )
            )
            ->addValidation(dkgValidation::create('tumorstatus')
                ->addField(dkgValidationField::create('datum_sicherung'))
                ->addField(dkgValidationField::create('sicherungsgrad'))
                ->addField(dkgValidationField::create('datum_beurteilung'))
                ->addField(dkgValidationField::create('anlass'))
                ->addField(dkgValidationField::create('diagnose'))
                ->addField(dkgValidationField::create('morphologie'))
                ->addField(dkgValidationField::create('t'))
                ->addField(dkgValidationField::create('n'))
                ->addField(dkgValidationField::create('m'))
                ->addField(dkgValidationField::create('estro_urteil'))
                ->addField(dkgValidationField::create('prog_urteil'))
                ->addField(dkgValidationField::create('her2')
                    ->setCondition('substr($morphologie, -2) != "/2"')
                )
                ->addField(dkgValidationField::create('her2_methode')
                    ->setCondition('substr($morphologie, -2) != "/2"')
                )
                ->addField(dkgValidationField::create('her2_urteil')
                    ->setCondition('substr($morphologie, -2) != "/2"')
                )
                ->addField(dkgValidationField::create('rezidiv_lokal')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('rezidiv_lk')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('rezidiv_metastasen')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('nur_zweitmeinung')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('nur_diagnosesicherung')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('kein_fall')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('diagnose_seite')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_bef')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('g')
                    ->setCondition('substr($t, 0, 1) == "p" && in_array($tnm_praefix, array("y", "yr")) === false')
                )
                ->addField(dkgValidationField::create('l')
                    ->setCondition('substr($t, 0, 1) == "p"')
                )
                ->addField(dkgValidationField::create('v')
                    ->setCondition('substr($t, 0, 1) == "p"')
                )
                ->addField(dkgValidationField::create('l')
                    ->setCondition('substr($t, 0, 1) == "p"')
                )
                ->addField(dkgValidationField::create('resektionsrand')
                    ->setCheck(false)
                    ->setCondition('substr($t, 0, 1) == "p"')
                )
            )
        ;

        return $this;
    }
}

?>
