<?php

/*
 * AlcedisMED
 * Copyright (C) 2010-2016  Alcedis GmbH
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */ 

class dkgGtValidations extends dkgBaseValidations
{
    public function __construct()
    {
        $this
            ->_setName('gt')
            ->_activateForDisease('gt')
            ->registerValidations()
        ;
    }

    public function registerValidations()
    {
        $this
            ->addValidation(dkgValidation::create('vorlage_studie')
                ->addField(dkgValidationField::create('ethikvotum')
                     ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('vorlage_therapie')
                ->addField(dkgValidationField::create('vorlage_therapie_id'))
                ->addDlist(dkgValidation::create('vorlage_therapie_wirkstoff')
                    ->addField(dkgValidationField::create('dosis')
                        ->setCheck(false)
                    )
                    ->addField(dkgValidationField::create('zyklus_beginn'))
                    ->addField(dkgValidationField::create('zyklus_anzahl'))
                    ->addField(dkgValidationField::create('zyklustag')
                            ->setCheck(false)
                    )
                )
            )
            ->addValidation(dkgValidation::create('diagnose')
                ->addField(dkgValidationField::create('datum'))
            )
            ->addValidation(dkgValidation::create('eingriff')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('operateur1_id')
                    ->setCondition('$org_id == "$patientOrgId" || strlen($org_id) == 0')
                )
                ->addField(dkgValidationField::create('operateur2_id')
                    ->setCheck(false)
                    ->setCondition('($org_id == "$patientOrgId" || strlen($org_id) == 0) && in_array("1", array($art_primaertumor, $art_lk, $art_metastasen, $art_rezidiv, $art_nachresektion, $art_revision)) === true')
                )
                ->addField(dkgValidationField::create('art_staging')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('art_primaertumor')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('art_rezidiv')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('art_revision')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('laparotomie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('peritonealzytologie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('peritonealbiopsie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('adnexexstirpation')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('hysterektomie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('omentektomie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lymphonodektomie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('tumorrest'))
                ->addField(dkgValidationField::create('tumorrest_groesse')
                    ->setCheck(false)
                )
                ->addDlist(dkgValidation::create('eingriff_ops')
                    ->addField(dkgValidationField::create('prozedur'))
                )
            )
            ->addValidation(dkgValidation::create('komplikation')
                ->addField(dkgValidationField::create('zeitpunkt')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('revisionsoperation'))
            )
            ->addValidation(dkgValidation::create('histologie')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('art'))
                ->addField(dkgValidationField::create('groesste_ausdehnung')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('kapseldurchbruch')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('invasionstiefe')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('invasionsbreite')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('groesse_x')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_bef')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_pelvin_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_pelvin_bef')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_para_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('lk_para_bef')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('therapieplan')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('grundlage'))
                ->addField(dkgValidationField::create('zeitpunkt'))
                ->addField(dkgValidationField::create('konferenz_patient_id')
                     ->setCondition('$grundlage == "tk" && appSettings::get("konferenz") === true')
                )
                ->addField(dkgValidationField::create('strahlen_indiziert'))
            )
            ->addValidation(dkgValidation::create('studie')
                ->addField(dkgValidationField::create('vorlage_studie_id'))
                ->addField(dkgValidationField::create('date')
                    ->setCondition('strlen($beginn) == 0')
                )
                ->addField(dkgValidationField::create('beginn')
                    ->setCondition('strlen($date) == 0')
                )
            )
            ->addValidation(dkgValidation::create('beratung')
                ->addField(dkgValidationField::create('datum'))
                ->addField(dkgValidationField::create('psychoonkologie'))
                ->addField(dkgValidationField::create('psychoonkologie_dauer')
                    ->setCondition('$psychoonkologie == 1')
                )
                ->addField(dkgValidationField::create('sozialdienst'))
            )
            ->addValidation(dkgValidation::create('fragebogen')
                ->addField(dkgValidationField::create('datum'))
            )
            ->addValidation(dkgValidation::create('abschluss')
                ->addField(dkgValidationField::create('abschluss_grund'))
                ->addField(dkgValidationField::create('todesdatum')
                    ->setCheck(false)
                    ->setCondition('$abschluss_grund == "tot"')
                )
                ->addField(dkgValidationField::create('tod_tumorassoziation')
                    ->setCheck(false)
                    ->setCondition('$abschluss_grund == "tot"')
                )
            )
            ->addValidation(dkgValidation::create('tumorstatus')
                ->addField(dkgValidationField::create('datum_sicherung'))
                ->addField(dkgValidationField::create('sicherungsgrad'))
                ->addField(dkgValidationField::create('datum_beurteilung'))
                ->addField(dkgValidationField::create('anlass'))
                ->addField(dkgValidationField::create('diagnose'))
                ->addField(dkgValidationField::create('lokalisation')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('rezidiv_lokal')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('rezidiv_lk')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('rezidiv_metastasen')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('nur_zweitmeinung')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('nur_diagnosesicherung')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('kein_fall')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('morphologie'))
                ->addField(dkgValidationField::create('lk_entf')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('t'))
                ->addField(dkgValidationField::create('n'))
                ->addField(dkgValidationField::create('m'))
                ->addField(dkgValidationField::create('g')
                    ->setCondition('substr($t, 0, 1) == "p" && in_array($tnm_praefix, array("y", "yr")) === false')
                )
                ->addField(dkgValidationField::create('r_lokal')
                    ->setCheck(false)
                    ->setCondition('substr($t, 0, 1) == "p"')
                )
                ->addField(dkgValidationField::create('figo')
                    ->setCondition('strlen($t) == 0 || strlen($n) == 0 || strlen($m) == 0')
                )
                ->addField(dkgValidationField::create('lk_staging')
                    ->setCheck(false)
                )
            )
            ->addValidation(dkgValidation::create('nachsorge')
                ->addField(dkgValidationField::create('datum'))
            )
            ->addValidation(dkgValidation::create('therapie_systemisch')
                ->addField(dkgValidationField::create('therapielinie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('studie')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('ende')
                    ->setCheck(false)
                )
                ->addField(dkgValidationField::create('tumorverhalten_platin')
                    ->setCheck(false)
                )
            )
        ;

        return $this;
    }
}

?>
